{
 "title": "99chat OpenIM 数据监控",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rpcNameFilter", "label": "filter", "query": "openimserver-openim-rpc.*" },
   { "name": "legendName", "label": "legend", "query": "{{job}}: {{instance}}" },
   {
    "name": "time",
    "label": "time",
    "query": "1m,5m,30m,1h,3h,6h,12h,24h,1w,4w,12w,24w,1y,2y,4y,10y"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "timeseries",
   "description": "Is the service up.",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "up", "legendFormat": "$legendName" }
   ]
  },
  {
   "title": "Login Information",
   "type": "timeseries",
   "description": "This metric represents the number of online users and login users within the time frame.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "online_user_num", "legendFormat": "online users" },
    {
     "expr": "increase(user_login_total[$time])",
     "legendFormat": "login num"
    }
   ]
  },
  {
   "title": "Register num",
   "type": "timeseries",
   "description": "This metric represents the number of register users within the time frame.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "user_register_total", "legendFormat": "register users" }
   ]
  },
  {
   "title": "Chat Msg Success Num",
   "type": "timeseries",
   "description": "This metric represents the number of chat msg success.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(single_chat_msg_process_success_total[$time])",
     "legendFormat": "single msgs"
    },
    {
     "expr": "increase(group_chat_msg_process_success_total[$time])",
     "legendFormat": "group msgs"
    }
   ]
  },
  {
   "title": "Chat Msg Failed Num",
   "type": "timeseries",
   "description": "This metric represents the number of chat msg failed .",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(single_chat_msg_process_failed_total[$time])",
     "legendFormat": "single msgs"
    },
    {
     "expr": "increase(group_chat_msg_process_failed_total[$time])",
     "legendFormat": "group msgs"
    }
   ]
  },
  {
   "title": "Msg Offline Push Failed Num",
   "type": "timeseries",
   "description": "This metric represents the number of msg failed offline pushed.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(msg_offline_push_failed_total[$time])",
     "legendFormat": "addr:{{instance}}"
    }
   ]
  },
  {
   "title": "Seq Set Failed Num",
   "type": "timeseries",
   "description": "This metric represents the number of failed set seq.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(seq_set_failed_total[$time])",
     "legendFormat": "addr: {{instance}}"
    }
   ]
  },
  {
   "title": "Long Time Send Msg Total",
   "type": "timeseries",
   "description": "This metric represents the number of messages that take a long time to send.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "msg_long_time_push_total", "legendFormat": "addr:{{instance}}" }
   ]
  },
  {
   "title": "Msg Success Insert Num",
   "type": "timeseries",
   "description": "This metric represents the number of successfully inserted messages.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(msg_insert_redis_success_total[$time])",
     "legendFormat": "redis: {{instance}}"
    },
    {
     "expr": "increase(msg_insert_mongo_success_total[$time])",
     "legendFormat": "mongo: {{instance}}"
    }
   ]
  },
  {
   "title": "Msg Failed Insert Num",
   "type": "timeseries",
   "description": "This metric represents the number of failed insertion messages.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(msg_insert_redis_failed_total[$time])",
     "legendFormat": "redis: {{instance}}"
    },
    {
     "expr": "increase(msg_insert_mongo_failed_total[$time])",
     "legendFormat": "mongo: {{instance}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Requests Total",
     "type": "timeseries",
     "description": "This metric represents the number of call of all API.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum by (path) (api_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "API Requests Num",
     "type": "timeseries",
     "description": "This metric represents the number of call of all API within the time frame.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (increase(api_count[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Error Total",
     "type": "timeseries",
     "description": "This metric represents the number of err return of API.",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (api_count{code != \"0\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Error Total With Code",
     "type": "timeseries",
     "description": "This metric represents the number of err return of API with err code.",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path, code) (api_count{code != \"0\"})",
       "legendFormat": "{{path}}: code={{code}}"
      }
     ]
    },
    {
     "title": "API QPS",
     "type": "timeseries",
     "description": "This metric represents the qps of API.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      { "expr": "sum(rate(api_count[1m]))", "legendFormat": "qps" }
     ]
    },
    {
     "title": "API Error Num",
     "type": "timeseries",
     "description": "This metric represents the number of err return of API within the time frame.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (increase(api_count{code != \"0\"}[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Error Num With Code",
     "type": "timeseries",
     "description": "This metric represents the number of err return of API with err code within the time frame..",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path, code) (increase(api_count{code != \"0\"}[$time]))",
       "legendFormat": "{{path}}: code={{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Total Count",
     "type": "timeseries",
     "description": "This metric represents the number of call of all RPC.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum by (path) (rpc_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "RPC Error Count",
     "type": "timeseries",
     "description": "This metric represents the error return of RPC.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (rpc_count{code!=\"0\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Error Count With Code",
     "type": "timeseries",
     "description": "This metric represents the error return of RPC with code.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path, code) (rpc_count{code!=\"0\"})",
       "legendFormat": "{{path}}: code={{code}}"
      }
     ]
    },
    {
     "title": "RPC Total Num",
     "type": "timeseries",
     "description": "This metric represents the number of call of all RPC within the time frame.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (increase(rpc_count[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Num by Name",
     "type": "timeseries",
     "description": "This metric represents the number of RPC calls within the time frame, aggregated by name.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(rpc_count[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Num by Address",
     "type": "timeseries",
     "description": "This metric represents the number of call of RPC within the time frame, aggregated by address.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (increase(rpc_count[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Error Num",
     "type": "timeseries",
     "description": "This metric represents the error return of RPC within the time frame within the time frame.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path) (increase(rpc_count{code!=\"0\"}[$time]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Error Num With Code",
     "type": "timeseries",
     "description": "This metric represents the error return of RPC with code within the time frame within the time frame.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (path, code) (increase(rpc_count{code!=\"0\"}[$time]))",
       "legendFormat": "{{path}}: code={{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Total Count",
     "type": "timeseries",
     "description": "This metric represents the number of HTTP requests.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, path) (http_count)",
       "legendFormat": "{{method}}: {{path}}"
      }
     ]
    },
    {
     "title": "HTTP Total Count With Status",
     "type": "timeseries",
     "description": "This metric represents the number of HTTP requests with status.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, path, status) (http_count)",
       "legendFormat": "{{method}}: {{path}}: {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Total Num",
     "type": "timeseries",
     "description": "This metric represents the number of HTTP requests within the time frame.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, path) (increase(http_count[$time]))",
       "legendFormat": "{{method}}: {{path}}"
      }
     ]
    },
    {
     "title": "HTTP Total Num With Status",
     "type": "timeseries",
     "description": "This metric represents the number of HTTP requests with status within the time frame.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, path, status) (increase(http_count[$time]))",
       "legendFormat": "{{method}}: {{path}}: {{status}}"
      }
     ]
    },
    {
     "title": "HTTP QPS",
     "type": "timeseries",
     "description": "This metric represents the qps of HTTP.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      { "expr": "sum(rate(http_count[1m]))", "legendFormat": "qps" }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Percentage",
     "type": "timeseries",
     "description": "This metric represents the proportion of CPU runtime within 1 second. It is calculated as the average CPU runtime over 1 minute.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  rate(process_cpu_seconds_total{job=~\"$rpcNameFilter\"}[1m])*100,\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage Percentage",
     "type": "timeseries",
     "description": "This metric represents the proportion of CPU runtime within 1 second. It is calculated as the average CPU runtime over 1 minute.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  rate(process_cpu_seconds_total{job!~\"$rpcNameFilter\"}[1m])*100,\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "This metric represents the number of open file descriptors.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_open_fds{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "This metric represents the number of open file descriptors.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_open_fds{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Virtual Memory bytes",
     "type": "timeseries",
     "description": "This metric represents the number of process virtual memory bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_virtual_memory_bytes{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Virtual Memory bytes",
     "type": "timeseries",
     "description": "This metric represents the number of process virtual memory bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_virtual_memory_bytes{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Resident Memory bytes",
     "type": "timeseries",
     "description": "This metric represents the number of process resident memory bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_resident_memory_bytes{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Resident Memory bytes",
     "type": "timeseries",
     "description": "This metric represents the number of process resident memory bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  process_resident_memory_bytes{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GO infomation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Rate Per Second",
     "type": "timeseries",
     "description": "Measures the frequency of garbage collection operations in the Go environment, averaged over the last five minutes.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  rate(go_gc_duration_seconds_count{job=~\"$rpcNameFilter\"}[5m]),\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "GC Rate Per Second",
     "type": "timeseries",
     "description": "Measures the frequency of garbage collection operations in the Go environment, averaged over the last five minutes.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  rate(go_gc_duration_seconds_count{job!~\"$rpcNameFilter\"}[5m]),\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "This metric represents the number of goroutines.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_goroutines{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "This metric represents the number of goroutines.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_goroutines{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Alloc Bytes ",
     "type": "timeseries",
     "description": "This metric represents the number of bytes allocated and still in use.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_alloc_bytes{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Alloc Bytes ",
     "type": "timeseries",
     "description": "This metric represents the number of bytes allocated and still in use.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_alloc_bytes{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Buck Hash Sys Bytes ",
     "type": "timeseries",
     "description": "This metric represents the number of bytes used by the profiling bucket hash table.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_buck_hash_sys_bytes{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Buck Hash Sys Bytes ",
     "type": "timeseries",
     "description": "This metric represents the number of bytes used by the profiling bucket hash table.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_buck_hash_sys_bytes{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Mcache Bytes",
     "type": "timeseries",
     "description": "This metric represents the number of bytes in use by mcache structures.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_mcache_inuse_bytes{job=~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    },
    {
     "title": "Go Mcache Bytes",
     "type": "timeseries",
     "description": "This metric represents the number of bytes in use by mcache structures.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  go_memstats_mcache_inuse_bytes{job!~\"$rpcNameFilter\"},\r\n  \"job\",\r\n  \"$1\",\r\n  \"job\",\r\n  \".*openim-(.*)\"\r\n)",
       "legendFormat": "$legendName"
      }
     ]
    }
   ]
  }
 ]
}