import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const context = vm.createContext({});
vm.runInContext(readFileSync(new URL('./batch-users.js', import.meta.url), 'utf8'), context);
const { parseRows, runBatch } = context.AdminBatchCore;
const input = '甲,a@example.com,13800138001,secret\n乙,b@example.com,,secret';
const rows = parseRows(input);
assert.equal(rows.length, 2);
assert.equal(rows[1].areaCode, '');
assert.throws(() => parseRows(input + '\n丙,a@example.com,,secret'), /重复/);
assert.throws(() => parseRows(input + '\n丙,c@example.com,13800138001,secret'), /重复/);
assert.throws(() => parseRows('甲,invalid,,secret'), /有效邮箱/);
assert.throws(() => parseRows(Array.from({ length: 51 }, (_, i) => `甲,a${i}@example.com,,secret`).join('\n')), /50/);
let calls = 0;
await runBatch(rows, async () => {
  calls++;
  if (calls === 1) return { data: { userID: 'test-user' } };
  throw 'EmailAlreadyRegister';
}, () => {});
assert.equal(rows[0].status, '成功');
assert.equal(rows[0].result, 'test-user');
assert.equal(rows[1].status, '失败');
assert.equal(rows[1].result, '邮箱已注册');
assert.equal(calls, 2);
assert.ok(rows.every(row => !row.password));
const uncertain = parseRows(input);
calls = 0;
await runBatch(uncertain, async () => { calls++; throw new Error('network'); }, () => {});
assert.equal(calls, 1);
assert.equal(uncertain[0].status, '结果待确认');
assert.equal(uncertain[1].status, '待创建');
assert.ok(uncertain.every(row => !row.password));
const serverFailure = parseRows(input);
calls = 0;
await runBatch(serverFailure, async () => { calls++; throw 'InternalServerError'; }, () => {});
assert.equal(calls, 1);
assert.equal(serverFailure[0].status, '结果待确认');
console.log('PASS batch validation, sequential outcomes, password clearing and unknown result stops queue');
