const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { randomUUID } = require('node:crypto');
const BASE = process.env.E2E_BASE || 'http://127.0.0.1:5199';
const API = process.env.E2E_CHAT_API || 'http://localhost:10008';
const code = process.env.TEST_VERIFY_CODE;
assert.ok(code, 'TEST_VERIFY_CODE is required in an isolated test environment');
async function request(path, body, token = '') {
  return (await fetch(`${API}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', operationID: randomUUID(), token }, body: JSON.stringify(body) })).json();
}
(async () => {
  const email = `auth-${Date.now()}@example.com`, phoneNumber = `139${String(Date.now()).slice(-8)}`;
  const password = randomUUID(), newPassword = randomUUID();
  const browser = await chromium.launch({ headless: true });
  let page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  try {
    page.setDefaultTimeout(30000);
    await page.goto(`${BASE}/#/auth/sign-in`);
    await page.getByRole('button', { name: '注册', exact: true }).first().click();
    await page.getByPlaceholder('请输入昵称').fill('email-auth-qa');
    await page.getByPlaceholder('请输入邮箱', { exact: true }).fill(email);
    await page.getByPlaceholder('请输入手机号').fill(phoneNumber);
    await page.getByRole('button', { name: '+86', exact: true }).click();
    await page.getByRole('button', { name: '+60 马来西亚', exact: true }).click();
    await page.getByPlaceholder('请输入邮箱验证码').fill(code);
    await page.getByPlaceholder('请输入密码', { exact: true }).fill(password);
    await page.getByPlaceholder('请再次输入密码').fill('mismatch');
    await page.getByRole('button', { name: '注册', exact: true }).last().click();
    await page.getByText('两次输入的密码不一致', { exact: true }).waitFor();
    await page.getByPlaceholder('请再次输入密码').fill(password);
    const registered = page.waitForResponse(res => res.url().endsWith('/account/register'));
    await page.getByRole('button', { name: '注册', exact: true }).last().click();
    const reg = await (await registered).json(); assert.equal(reg.errCode, 0, reg.errMsg);
    await page.waitForURL('**/#/messages');
    const token = reg.data.chatToken, uid = reg.data.userID;
    const profile = await request('/user/contact/get', {}, token);
    assert.equal(profile.errCode, 0, profile.errMsg);
    assert.deepEqual(profile.data, { phoneNumber, areaCode: '+60', email });
    assert.notEqual((await request('/account/login', { phoneNumber, areaCode: '+60', password, platform: 5 })).errCode, 0, 'Contact phone cannot authenticate');
    assert.notEqual((await request('/user/contact/save', { phoneNumber, areaCode: '+60' })).errCode, 0);
    const logged = await request('/account/login', { email, password, platform: 5 });
    assert.equal(logged.errCode, 0, logged.errMsg); assert.equal(logged.data.userID, uid);
    assert.equal((await request('/user/contact/get', {}, logged.data.chatToken)).data.phoneNumber, phoneNumber);
    await page.evaluate(() => localStorage.clear()); await page.goto(`${BASE}/#/auth/sign-in`); await page.reload();
    const requests = [];
    page.on('request', req => { if (req.url().endsWith('/account/code/send')) requests.push(req.postDataJSON()); });
    await page.getByRole('button', { name: '验证码登录', exact: true }).click();
    await page.getByPlaceholder('请输入邮箱', { exact: true }).fill(email);
    await page.getByRole('button', { name: '获取验证码', exact: true }).click();
    await page.getByRole('button', { name: /秒后重发/ }).waitFor(); assert.equal(requests.at(-1).usedFor, 3);
    await page.getByPlaceholder('请输入邮箱验证码').fill(code);
    const otp = page.waitForResponse(res => res.url().endsWith('/account/login'));
    await page.getByRole('button', { name: '登录', exact: true }).click();
    const otpLogin = await (await otp).json(); assert.equal(otpLogin.errCode, 0, otpLogin.errMsg); assert.equal(otpLogin.data.userID, uid);
    assert.equal(requests.length, 1); await page.waitForURL('**/#/messages');
    await page.close();
    page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    page.on('request', req => { if (req.url().endsWith('/account/code/send')) requests.push(req.postDataJSON()); });
    await page.goto(`${BASE}/#/auth/sign-in`);
    await page.getByRole('link', { name: '忘记密码？' }).click();
    await page.getByRole('heading', { name: '重置密码', exact: true }).waitFor();
    await page.getByPlaceholder('请输入邮箱').fill(email);
    await page.waitForFunction(value => document.querySelector('input[type="email"]').value === value, email);
    const sent = page.waitForResponse(res => res.url().endsWith('/account/code/send'));
    await page.getByRole('button', { name: '获取验证码', exact: true }).click();
    assert.equal((await (await sent).json()).errCode, 0); assert.equal(requests.at(-1).usedFor, 2);
    await page.getByPlaceholder('请输入验证码').fill('wrong-code');
    await page.getByPlaceholder('请输入新密码', { exact: true }).fill(newPassword);
    await page.getByPlaceholder('请再次输入新密码').fill(newPassword);
    const badReset = page.waitForResponse(res => res.url().endsWith('/account/password/reset'));
    await page.getByRole('button', { name: '重置密码', exact: true }).click();
    assert.notEqual((await (await badReset).json()).errCode, 0); await page.getByRole('alert').waitFor();
    await page.getByPlaceholder('请输入验证码').fill(code);
    await page.getByRole('button', { name: '重置密码', exact: true }).click(); await page.getByRole('status').waitFor();
    assert.notEqual((await request('/account/login', { email, password, platform: 5 })).errCode, 0);
    const changed = await request('/account/login', { email, password: newPassword, platform: 5 });
    assert.equal(changed.errCode, 0, changed.errMsg); assert.equal(changed.data.userID, uid);
    await page.screenshot({ path: '/tmp/99chat-email-reset.png' });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const legacy = await request('/account/register', { verifyCode: code, platform: 5, autoLogin: true, user: { phoneNumber, areaCode: '+86', nickname: 'legacy-qa', password } });
    assert.equal(legacy.errCode, 0, legacy.errMsg);
    const boundEmail = `legacy-${Date.now()}@example.com`, lt = legacy.data.chatToken;
    assert.notEqual((await request('/user/email/bind', { email: boundEmail, verifyCode: 'wrong-code' }, lt)).errCode, 0);
    assert.notEqual((await request('/user/update', { userID: legacy.data.userID, email: boundEmail }, lt)).errCode, 0);
    await page.goto(`${BASE}/#/auth/sign-in`);
    await page.getByRole('button', { name: '旧账号手机号登录', exact: true }).click();
    await page.getByPlaceholder('请输入手机号').fill(phoneNumber);
    await page.getByPlaceholder('请输入密码', { exact: true }).fill(password);
    await page.getByRole('button', { name: '登录', exact: true }).click();
    await page.waitForURL('**/#/messages');
    await page.goto(`${BASE}/#/settings/security`);
    await page.getByPlaceholder('请输入要绑定的邮箱').fill(boundEmail);
    const bindSent = page.waitForResponse(res => res.url().endsWith('/account/code/send'));
    await page.getByRole('button', { name: '获取验证码', exact: true }).click();
    assert.equal((await (await bindSent).json()).errCode, 0);
    await page.getByPlaceholder('请输入邮箱验证码').fill(code);
    await page.getByRole('button', { name: '验证并绑定邮箱', exact: true }).click();
    await page.getByText('邮箱绑定成功，可用于登录和找回密码', { exact: true }).waitFor();
    const bound = await request('/account/login', { email: boundEmail, password, platform: 5 });
    assert.equal(bound.errCode, 0, bound.errMsg); assert.equal(bound.data.userID, legacy.data.userID);
    assert.equal((await request('/account/login', { phoneNumber, areaCode: '+86', password, platform: 5 })).errCode, 0);
    assert.equal((await request('/account/password/change', { userID: legacy.data.userID, currentPassword: password, newPassword }, lt)).errCode, 0);
    assert.equal((await request('/account/login', { email: boundEmail, password: newPassword, platform: 5 })).errCode, 0);
    console.log('PASS email registration, durable contact, password/OTP login, recovery, verified legacy binding, authenticated password change');
  } catch (error) { console.error(await page.locator("body").innerText()); await page.screenshot({ path: "/tmp/99chat-email-test-error.png" }); throw error; } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
