import assert from 'node:assert/strict';
import { groupPermissions } from './src/utils/group-permissions.ts';
const members = [{ userID: 'owner', roleLevel: 100 }, { userID: 'admin', roleLevel: 60 }, { userID: 'admin2', roleLevel: 60 }, { userID: 'member', roleLevel: 20 }];
const owner = groupPermissions('owner', 'owner', members);
const admin = groupPermissions('owner', 'admin', members);
const member = groupPermissions('owner', 'member', members);
assert.equal(owner.canManage, true);
assert.equal(owner.canManageMember(members[1]), true);
assert.equal(owner.canManageMember(members[0]), false);
assert.equal(admin.canManage, true);
assert.equal(admin.isOwner, false);
assert.equal(admin.canManageMember(members[3]), true);
assert.equal(admin.canManageMember(members[2]), false);
assert.equal(admin.canManageMember(members[0]), false);
assert.equal(member.canManage, false);
assert.equal(member.canInvite, true);
assert.equal(member.canManageMember(members[1]), false);
assert.equal(groupPermissions(undefined, undefined, []).canManage, false);
assert.equal(groupPermissions('owner', 'unknown', []).canInvite, false);
assert.equal(groupPermissions('owner', 'owner', []).canManage, true);
assert.equal(groupPermissions('owner', 'admin', [{ userID: 'admin', roleLevel: 20 }]).canManage, false);
console.log('PASS: owner, admin, ordinary member, loading and demotion permissions');
