const { chromium } = require('playwright');
const BASE = 'http://localhost:5199';
const SOURCE = `引用原文-${Date.now()}`;
const REPLY = `引用回复-${Date.now()}`;
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto(`${BASE}/#/auth/sign-in`);
  await page.getByPlaceholder('请输入手机号').fill('13800138000');
  await page.getByPlaceholder('请输入密码').fill('test123456');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.waitForURL(/#\/messages/, { timeout: 60000 });
  const conversation = page.locator('.cursor-pointer').filter({ hasText: 'suxia' }).first();
  await conversation.waitFor({ state: 'visible', timeout: 90000 });
  await conversation.click();
  const input = page.getByPlaceholder('输入消息...');
  await input.fill(SOURCE);
  await input.press('Enter');
  const source = page.locator('div').filter({ hasText: new RegExp(`^${SOURCE}$`) }).last();
  await source.waitFor({ state: 'visible', timeout: 15000 });
  await source.click({ button: 'right' });
  await page.getByText('回复', { exact: true }).click();
  await input.fill(REPLY);
  await input.press('Enter');
  await page.getByText(REPLY, { exact: true }).waitFor({ state: 'visible', timeout: 15000 });
  await page.getByText(SOURCE, { exact: true }).last().waitFor({ state: 'visible', timeout: 15000 });
  console.log('Quote message renders both reply text and referenced source text.');
  await browser.close();
})().catch((error) => { console.error(error); process.exit(1); });
